server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  resources:
    static-locations: classpath:/webapp/
